image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3333
    onOpen: ignore
  - port: 4200
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "MongoDB"
    command: |
      mkdir -p /workspace/data
      mongod --dbpath /workspace/data
  - name: "api"
    command: npm run start api
  - name: "price-search"
    command: npm run start
  - init: | # runs during prebuild
      ng analytics ci
      npm install
      npm run build
      npm run build api

vscode:
  extensions:
    - DavidAnson.vscode-markdownlint@0.34.0:l4DL7iPpo7DdhfUHIUtcuQ==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.3:MioHhlbqHKgivweg8MqHrA==
    - nrwl.angular-console@11.1.3:CRhVLJE38C6anNUGZjNQLA==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - johnpapa.Angular2@9.1.2:zMaYqbaVrWgYWYWDtzoAqw==
    - PKief.material-icon-theme@4.0.1:uW65d0I1ibFxFDWPtc2zkQ==
    - dracula-theme.theme-dracula@2.20.0:3ytFGkwBUqAAYaWVrFDm3w==
    - VisualStudioExptTeam.vscodeintellicode@1.2.6:Gl+8u7mnb+vYq2Ruvcx9/Q==
    - eg2.vscode-npm-script@0.3.11:peDPJqeL8FmmJiabU4fAJQ==
    - Angular.ng-template@0.900.12:3PfScC54anNZTUzYDDhzAw==
    - ashinzekene.nestjs@1.4.0:AkD5nGSQKUH/DgLg/+4p4Q==
    - Orta.vscode-jest@3.1.1:LQ3p9BsZrD/DSsU8zMC01g==