image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3333
    onOpen: ignore
  - port: 4200
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "MongoDB"
    command: |
      mkdir -p /workspace/data
      mongod --dbpath /workspace/data
  - name: "api"
    command: npm run start api
  - name: "price-search"
    command: npm run start
  - init: | # runs during prebuild
      ng analytics ci
      npm install
      npm run build
      npm run build api

vscode:
  extensions:
    - DavidAnson.vscode-markdownlint@0.34.0:l4DL7iPpo7DdhfUHIUtcuQ==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.3:MioHhlbqHKgivweg8MqHrA==
    - nrwl.angular-console@11.1.3:CRhVLJE38C6anNUGZjNQLA==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - johnpapa.Angular2@9.1.2:zMaYqbaVrWgYWYWDtzoAqw==
    - Angular.ng-template@0.900.15:UwgNni1v/oxE+UMAOJsWZg==
